### ISSUE TITLE
Documentation for a slight rewrite

### ISSUE THREAD

**Issue by aslakjo** [ifm/python-opd100-example#1]
Hi

Thank you for the project, it is very help full for our investigation of the opd100. However we are trying to port this example to useing the AY1020 and its webserver.

The problem is to understand th buildPDout on opd100_load.py:228. It builds an byte array that is sent to the Process data output. However the docuemntation we are looking at does not match. 

The fram number is not mentioned in the pdf found on ifm pages. https://www.ifm.com/il/en/product/OPD100?tab=details
![2022-01-12_15-23](https://user-images.githubusercontent.com/28076/149159556-684dcd53-0c33-4e87-8725-3b091999ebee.png)

Can you help us out, with more documentation?

**Comment by MatthiasAbtIfm** [comment]
Hi,

I can provide you more documentation about the process data output here: [Software specification - English (GB) Customer-specific information of the process data format (chapter 3)](https://www.ifm.com/mounting/80292544UK.pdf#%5B%7B%22num%22%3A45%2C%22gen%22%3A0%7D%2C%7B%22name%22%3A%22XYZ%22%7D%2C69%2C771%2C0%5D)

The opd100_load.py example uses the extended functionality for this.

**Comment by aslakjo** [comment]
Hi 

Thank you! That was all just what i was looking for :+1:
